### ISSUE TITLE
Callum Mellis in TK but not in file

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#103]
**Describe the bug**
In this error report Callum Mellis is shown as player from TK but not in file. On TK it is clear that there is something wrong with this player. You solved this earlier but after reingestion this list the issue popped up again.

https://discord.com/channels/910334907736272906/915385291429269505/932740426270642237

**Comment by duxbuse** [comment]
I believe that this is now resolved. since players with incomplete game history (they dropped part way through, or have game results out side 0-20) are now excluded. from my test run https://discord.com/channels/910334907736272906/915385291429269505/953816518385369138
it appears that scott jones needs to be also removed from the file as that was another player with dodgy data
