### ISSUE TITLE
Vermin Swarm has Vampire Data in it

### ISSUE THREAD

**Issue by modmoto** [duxbuse/ninthage-data-analytics#116]
If you open up the Internal Balance for Vermin Swarm, there are some entries from Vampires aswell. I guess a few games have wrong data?

![image](https://user-images.githubusercontent.com/9074759/161978424-0d8af8d5-e2ce-4584-b4bf-6a007cb1d10b.png)

**Comment by SanderND** [comment]
Root cause is an list recorded as Vermin but who are Vampire count.
Two consequences:

1) wrong units reported: i fix that by re-uploading this tourney
2) we dont monitor this to actively correct this. this could be done by adding armyname to the static unit data. When ARMYNAME from the results table doesnt equal ARMYNAME from static unit data, we know something is wrong as I just join on the unitname.

**Comment by SanderND** [comment]
After uploading the tourney this is corrected. Also a validation step will be added to prevent wrong uploads. Correctively i will check all records with the same issue and re-upload these tourneys.
