### ISSUE TITLE
Letz Play T9A not matched when loaded via bucket

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#79]
**Describe the bug**
I loaded Letz Play T9A to the bucket as the 'e' has two dots on it and cant be read by the bot, but still isnt matched to TK.

**To Reproduce**
1) upload attached file to bucket
2) see the result and no match to TK

**Expected behavior**
Match to tourney with same name on TK.

**Comment by duxbuse** [comment]
Ok this is an issue because Unicode is hella dumb
![image](https://user-images.githubusercontent.com/6869131/147802738-138927f3-b10e-4626-a4c1-e3583446df01.png)

Basically you are using the wrong letter.

You used `e%u0308` but it should have been `%EB`. But when rendered they look identical so its dumb.
So since I am ignoring punctuation now I will also try to decode any unicode back to ascii. Not sure how this will turn out but hopefully should catch most of these issues.
