### ISSUE TITLE
Tourneys to be deleted

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#82]
Please delete the following tourneys from DB as they are double or obsolete:

CR9 XV - Your bi-weekly dosis, ingested at December 15th
Verminsh ash, ingested at December 22nd
Letz play T9A, two times ingested at December 30th. Please delete both!

**Comment by duxbuse** [comment]
Ok so slight change of plan, since we are now ignoring all punctuation

I deleted ` New Year's Revolution` since we will just use ` New Years Revolution`  going forward
`CR9 XV - Your bi-weekly dosis` has been deleted
`Vermins ash The 9th Age Tournament`  gone
I also removed `Lëtz play T9A` favouring `Letz play T9A` going forward.

Note that when a file is uploaded all data from the same event(aka same file name) is first removed to ensure we dont get double ups.
Which means just reupload the file if you think there is an issue and it will remove all the old stuff before writing the new stuff. If it succeeds that is.

**Comment by SanderND** [comment]
Still quite some entries are removed. I see the following tourneynames which are to be removed:

Vermins ash The 9th Age Tour
Titans_of_9th_presents... 
Sanders test lists 4
Sanders test lists 5
Brisvegas Battles 3?
Baldin tes lists

Can you remove them?

P.s.: I filtered most of them out in Tableau, so you wont see them on the dashboard.

**Comment by duxbuse** [comment]
OK got rid of all these
